---
- name: Check Minikube status
  command: minikube status
  register: minikube_status
  changed_when: false
  failed_when: false

- name: Start Minikube if not running
  command: minikube start --driver=docker
  when: "'Running' not in minikube_status.stdout"

  # OLD -> da rimuovere
  # questo ti riscrive il kubeconfig host e può creare path /root/.minikube
  #
  # - name: Fix Minikube kubeconfig context
  #   command: minikube update-context

# NEW -> aggiorna context senza sporcare il tuo host config
- name: Fix Minikube kubeconfig context
  command: minikube update-context
  environment:
    CHANGE_MINIKUBE_NONE_USER: true
  changed_when: false

- name: Get Minikube IP
  command: minikube ip
  register: minikube_ip
  changed_when: false

- name: Show Minikube IP
  debug:
    var: minikube_ip.stdout

- name: Create namespace formazione-sou
  command: kubectl create namespace formazione-sou
  failed_when: false
  changed_when: false
